name: "swift-create-xcframework"
description: "Creates XCFramework bundles for yout Swift Package"

inputs:
  target:
    description: "The name of the target you want to create an XCFramework bundle for. Recommended if your Package.swift declares multiple library products. Can only be a single target at a time."
    required: false
  platforms:
    description: "The platform(s) that you want to build for. Default is to build for all platforms supported in your Package.swift, or all Apple platforms if omited. Comma-delimited string supported."
    required: false
  version:
    description: "A version number to use to tag the ZIP file with"
    required: false
  configuration:
    description: "Build with a specific configuration ('debug' or 'release')"
    required: false
    default: release

runs:
  using: node12
  main: action.js

branding:
  icon: "package"
  color: "green"